hbs/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :listings

  root 'listings#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hbs/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hbs/app/models/listing.rb
class Listing < ApplicationRecord
end

hbs/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

hbs/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def new
  end

  def create
    render plain: params[:listing].inspect
  end
end

hbs/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

hbs/app/helpers/application_helper.rb
module ApplicationHelper
end

hbs/app/helpers/listings_helper.rb
module ListingsHelper
end

hbs/app/helpers/welcome_helper.rb
module WelcomeHelper
end

hbs/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hbs</title>
    <%= csrf_meta_tags %>

  <!-- Styled out at request of specification -->
  <!--  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>

hbs/app/views/listings/new.html.erb
<h1> Create a new guestbook listing! </h1>


<%= form_with scope: :listing, url: listings_path, local: true do |form| %>
  <p>
    <%= form.label :message %><br>
    <%= form.text_area :message %>
  </p>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

hbs/app/views/welcome/index.html.erb
<h1>Hello, Happy Bear Software Team!</h1>
<p> Welcome to my Rails application!</p>